-- Migration: 0013_create_booking_outbox_events_table
-- Description: Creates `booking_outbox_events` — the Transactional Outbox
--              (Phase 16 Step 2) for booking-service's own domain events.
--              A business transaction (e.g. creating a booking) writes its
--              normal row AND a row here in the SAME database transaction,
--              so the two can never disagree: an event exists if and only
--              if the state change it describes was actually committed. A
--              separate scheduled publisher (OutboxPublisher) reads PENDING
--              rows here and publishes them to Kafka independently, marking
--              PUBLISHED only after a real broker acknowledgement. See
--              docs/architecture.md §47.9 (the design) and §48 (this
--              implementation).
-- Depends on: nothing (aggregate_id is a plain UUID reference, not a FK —
--             this table must support any future aggregate type, not only
--             bookings; see the table comment below).

-- Table name is prefixed `booking_`, unlike every domain table so far
-- (bookings, payments, ...), because "outbox_events" is not a unique
-- domain noun the way those are — it is generic outbox-pattern
-- infrastructure that any future producing service (payment-service,
-- catalog-service, user-service) will eventually need its own copy of.
-- All of Eventtick's tables currently share one physical database
-- (docs/architecture.md §17: database-per-service is a future target, not
-- required today), so an unprefixed `outbox_events` name would collide the
-- moment a second service adds its own outbox table. The prefix avoids
-- that collision now rather than requiring a rename later.
CREATE TABLE booking_outbox_events (
    event_id        UUID          PRIMARY KEY,
    event_type      VARCHAR(100)  NOT NULL,
    aggregate_type  VARCHAR(50)   NOT NULL,
    aggregate_id    UUID          NOT NULL,
    topic           VARCHAR(100)  NOT NULL,
    payload         TEXT          NOT NULL,
    occurred_at     TIMESTAMPTZ   NOT NULL,
    status          VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    attempts        INT           NOT NULL DEFAULT 0,
    last_error      TEXT,
    published_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT chk_booking_outbox_events_status
        CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED')),
    CONSTRAINT chk_booking_outbox_events_attempts_nonneg
        CHECK (attempts >= 0),
    CONSTRAINT chk_booking_outbox_events_published_at_consistency
        CHECK (
            (status = 'PUBLISHED' AND published_at IS NOT NULL)
            OR (status <> 'PUBLISHED' AND published_at IS NULL)
        )
);

COMMENT ON TABLE booking_outbox_events IS
    'Transactional outbox for booking-service''s own domain events (Phase '
    '16 Step 2). event_id doubles as the Kafka message''s own eventId (the '
    'idempotency key downstream consumers dedupe on) and this table''s '
    'primary key, generated by the application when the row is created, '
    'not by the database — there is no separate surrogate id. No rows are '
    'deleted by this migration''s own code; a published row is retained, '
    'not pruned (see docs/architecture.md §48 for the retention decision).';
COMMENT ON COLUMN booking_outbox_events.event_id IS
    'The event envelope''s own eventId. Unique by construction (it is the '
    'primary key) — a genuine duplicate publish attempt (e.g. an outbox '
    'row re-read and re-sent after a crash between Kafka ack and this row '
    'being marked PUBLISHED) reuses the SAME event_id, which is exactly '
    'what lets a consumer recognize and ignore it.';
COMMENT ON COLUMN booking_outbox_events.event_type IS
    'E.g. ''BookingCreated'' — see docs/architecture.md §47.2''s catalogue.';
COMMENT ON COLUMN booking_outbox_events.aggregate_type IS
    'E.g. ''Booking'' — the envelope''s own aggregateType.';
COMMENT ON COLUMN booking_outbox_events.aggregate_id IS
    'The domain row''s own id (e.g. bookings.id) and the Kafka partition '
    'key the publisher sends with — guarantees per-aggregate ordering '
    '(docs/architecture.md §47.7). Deliberately not a foreign key: this '
    'table is generic outbox infrastructure, not booking-specific, and '
    'must be able to hold an id from any future aggregate type this '
    'service might someday publish events for.';
COMMENT ON COLUMN booking_outbox_events.topic IS
    'The target Kafka topic (e.g. ''eventtick.booking''), decided by the '
    'application at write time (see EventTopics) rather than re-derived by '
    'the publisher from aggregate_type — keeps the publisher itself fully '
    'generic, with zero domain-specific mapping logic of its own.';
COMMENT ON COLUMN booking_outbox_events.payload IS
    'The fully-serialized JSON event envelope (eventId, eventType, '
    'occurredAt, aggregateType/aggregateId, correlationId, causationId, '
    'and the domain payload, all nested together) — published to Kafka '
    'byte-for-byte unchanged. Plain TEXT, not JSONB: nothing in this '
    'design queries into the JSON via Postgres''s own JSON operators, only '
    'the application ever reads or writes it whole, so JSONB''s extra '
    'parsing/indexing capability would be unused complexity. Migrating the '
    'column type later, if a real need arises, is a one-line ALTER.';
COMMENT ON COLUMN booking_outbox_events.occurred_at IS
    'The business moment the event describes (e.g. when the booking row '
    'was actually committed) — matches the envelope''s own occurredAt, '
    'kept as a real column so the publisher can order PENDING rows by it '
    'without parsing the JSON payload.';
COMMENT ON COLUMN booking_outbox_events.status IS
    'One of: PENDING (not yet successfully published), PUBLISHED '
    '(acknowledged by Kafka), FAILED (reserved for a future max-retry/DLQ '
    'policy — see docs/architecture.md §48; no code path sets this yet, '
    'the same "defined but not yet reachable" precedent as '
    'bookings.status''s own FAILED value). Every publish failure today '
    'simply stays PENDING, with attempts incremented, for the next sweep.';
COMMENT ON COLUMN booking_outbox_events.attempts IS
    'How many times the publisher has tried to publish this row. '
    'Incremented on failure only; a successful publish does not increment '
    'it further. No maximum is enforced yet (no DLQ in this step).';
COMMENT ON COLUMN booking_outbox_events.last_error IS
    'The most recent publish failure''s message, for operator visibility. '
    'NULL if this row has never failed a publish attempt.';
COMMENT ON COLUMN booking_outbox_events.published_at IS
    'When this row was actually marked PUBLISHED — set once, only after a '
    'real Kafka broker acknowledgement, never merely because a send was '
    'initiated. NULL for every non-PUBLISHED row (enforced by '
    'chk_booking_outbox_events_published_at_consistency).';

-- The publisher's own query shape: PENDING rows, oldest first, a bounded
-- batch at a time. A partial index (only PENDING rows) keeps the sweep
-- cheap as the table grows, since PUBLISHED rows are retained and will
-- vastly outnumber PENDING ones in the steady state — the same "index
-- only what the sweep queries" reasoning already used for
-- idx_payments_booking_sync_status_pending in migration 0012.
--
-- Known test-environment limitation (see docs/architecture.md §25.4):
-- this project's H2 test version does not support partial/filtered
-- indexes, so this index is exercised only against the real PostgreSQL
-- migration, not by any H2-backed test — the same documented gap
-- uq_payments_one_active_per_booking already has.
CREATE INDEX idx_booking_outbox_events_pending_created_at
    ON booking_outbox_events (created_at)
    WHERE status = 'PENDING';

CREATE TRIGGER trg_booking_outbox_events_set_updated_at
    BEFORE UPDATE ON booking_outbox_events
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
