-- Migration: 0015_create_payment_outbox_events_table
-- Description: Creates `payment_outbox_events` — payment-service's own
--              Transactional Outbox (Phase 16 Step 4), the same pattern
--              proven by `booking_outbox_events` (migration 0013), a
--              separate copy rather than a shared table: payment-service
--              owns its own persistence boundary, exactly the same
--              reasoning that already keeps `payments` and `bookings` in
--              separate tables despite sharing one physical database (see
--              docs/architecture.md §17). A business transaction (a
--              payment reaching SUCCESS) writes its normal row AND a row
--              here in the SAME database transaction, so the two can never
--              disagree. A separate scheduled publisher
--              (PaymentOutboxPublisher) reads PENDING rows here and
--              publishes them to Kafka independently, marking PUBLISHED
--              only after a real broker acknowledgement. See
--              docs/architecture.md §50 for this step's design.
-- Depends on: nothing (aggregate_id is a plain UUID reference, not a FK —
--             same reasoning as booking_outbox_events.aggregate_id below).

-- Column-for-column identical shape to booking_outbox_events (migration
-- 0013) — the schema itself is genuinely reusable outbox infrastructure;
-- only the table (and therefore the physical row storage) is per-service,
-- not the design. See that migration's own comments for the full
-- reasoning behind each column and constraint; not repeated verbatim here
-- beyond what differs.
CREATE TABLE payment_outbox_events (
    event_id        UUID          PRIMARY KEY,
    event_type      VARCHAR(100)  NOT NULL,
    aggregate_type  VARCHAR(50)   NOT NULL,
    aggregate_id    UUID          NOT NULL,
    topic           VARCHAR(100)  NOT NULL,
    payload         TEXT          NOT NULL,
    occurred_at     TIMESTAMPTZ   NOT NULL,
    status          VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    attempts        INT           NOT NULL DEFAULT 0,
    last_error      TEXT,
    published_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ   NOT NULL DEFAULT now(),

    CONSTRAINT chk_payment_outbox_events_status
        CHECK (status IN ('PENDING', 'PUBLISHED', 'FAILED')),
    CONSTRAINT chk_payment_outbox_events_attempts_nonneg
        CHECK (attempts >= 0),
    CONSTRAINT chk_payment_outbox_events_published_at_consistency
        CHECK (
            (status = 'PUBLISHED' AND published_at IS NOT NULL)
            OR (status <> 'PUBLISHED' AND published_at IS NULL)
        )
);

COMMENT ON TABLE payment_outbox_events IS
    'Transactional outbox for payment-service''s own domain events (Phase '
    '16 Step 4), first used for PaymentSucceeded. event_id doubles as the '
    'Kafka message''s own eventId (the idempotency key downstream '
    'consumers dedupe on) and this table''s primary key, generated by the '
    'application when the row is created, not by the database. No rows '
    'are deleted by this migration''s own code; a published row is '
    'retained, not pruned (matches booking_outbox_events''s own retention '
    'decision, docs/architecture.md §48).';
COMMENT ON COLUMN payment_outbox_events.event_id IS
    'The event envelope''s own eventId. Unique by construction (it is the '
    'primary key) — a genuine duplicate publish attempt (e.g. this row '
    're-read and re-sent after a crash between Kafka ack and this row '
    'being marked PUBLISHED) reuses the SAME event_id, which is exactly '
    'what lets a consumer recognize and ignore it.';
COMMENT ON COLUMN payment_outbox_events.event_type IS
    'E.g. ''PaymentSucceeded'' — see docs/architecture.md §50''s catalogue.';
COMMENT ON COLUMN payment_outbox_events.aggregate_type IS
    'E.g. ''Payment'' — the envelope''s own aggregateType.';
COMMENT ON COLUMN payment_outbox_events.aggregate_id IS
    'The domain row''s own id (payments.id) and the Kafka partition key '
    'the publisher sends with — guarantees per-aggregate ordering, the '
    'same reasoning as booking_outbox_events.aggregate_id. Deliberately '
    'not a foreign key: this table is generic outbox infrastructure for '
    'this service, not payment-specific, and must be able to hold an id '
    'from any future aggregate type payment-service might someday publish '
    'events for.';
COMMENT ON COLUMN payment_outbox_events.topic IS
    'The target Kafka topic (''eventtick.payment''), decided by the '
    'application at write time (see EventTopics) rather than re-derived '
    'by the publisher from aggregate_type.';
COMMENT ON COLUMN payment_outbox_events.payload IS
    'The fully-serialized JSON event envelope, published to Kafka '
    'byte-for-byte unchanged. Plain TEXT, not JSONB, for the same reason '
    'as booking_outbox_events.payload: nothing queries into it via '
    'Postgres''s own JSON operators.';
COMMENT ON COLUMN payment_outbox_events.status IS
    'One of: PENDING (not yet successfully published), PUBLISHED '
    '(acknowledged by Kafka), FAILED (reserved for a future max-retry/DLQ '
    'policy — no code path sets this yet). Every publish failure today '
    'simply stays PENDING, with attempts incremented, for the next sweep.';
COMMENT ON COLUMN payment_outbox_events.attempts IS
    'How many times the publisher has tried to publish this row. '
    'Incremented on failure only. No maximum is enforced yet (no DLQ in '
    'this step).';
COMMENT ON COLUMN payment_outbox_events.last_error IS
    'The most recent publish failure''s message, for operator visibility. '
    'NULL if this row has never failed a publish attempt.';
COMMENT ON COLUMN payment_outbox_events.published_at IS
    'When this row was actually marked PUBLISHED — set once, only after a '
    'real Kafka broker acknowledgement, never merely because a send was '
    'initiated. NULL for every non-PUBLISHED row (enforced by '
    'chk_payment_outbox_events_published_at_consistency).';

-- Same partial-index reasoning as idx_booking_outbox_events_pending_created_at
-- (migration 0013): the publisher's own query shape is "PENDING rows,
-- oldest first, a bounded batch." Not exercised by H2-backed tests (same
-- documented limitation as that index and uq_payments_one_active_per_booking).
CREATE INDEX idx_payment_outbox_events_pending_created_at
    ON payment_outbox_events (created_at)
    WHERE status = 'PENDING';

CREATE TRIGGER trg_payment_outbox_events_set_updated_at
    BEFORE UPDATE ON payment_outbox_events
    FOR EACH ROW
    EXECUTE FUNCTION set_updated_at();
